#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" 

# Customize to your needs...

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/Users/mash/.gvm/bin/gvm-init.sh" ]] && source "/Users/mash/.gvm/bin/gvm-init.sh"

### Added by the Heroku Toolbelt
set SBT_HOME = /Users/mash/dev/tools/sbt-0.13.5
set SCALA_HOME = /Users/mash/dev/tools/scala-2.10.0-RC2
export PATH="/usr/local/heroku/bin:$SCALA_HOME/bin:$SBT_HOME/bin:$PATH"

export CLICOLOR=YES
export LSCOLORS="Gxfxcxdxbxegedabagacad"
